const wordList = [
    { word: "aodai", display: "Áo Dài", hint: "Trang phục truyền thống của phụ nữ Việt Nam." },
    { word: "hue", display: "Huế", hint: "Kinh đô cổ nổi tiếng với sông Hương, cầu Tràng Tiền." },
    { word: "halong", display: "Hạ Long", hint: "Vịnh nổi tiếng với hàng nghìn đảo đá, di sản thiên nhiên thế giới." },
    { word: "banhchung", display: "Bánh Chưng", hint: "Món bánh truyền thống không thể thiếu vào dịp Tết Nguyên Đán." },
    { word: "trungthu", display: "Trung Thu", hint: "Lễ hội dành cho thiếu nhi, thường có múa lân và đèn ông sao." },
    { word: "hanoi", display: "Hà Nội", hint: "Thủ đô ngàn năm văn hiến của Việt Nam." },
    { word: "caotrang", display: "Nón Cao Tràng", hint: "Loại nón truyền thống thường thấy ở miền Bắc." },
    { word: "dantranh", display: "Đàn Tranh", hint: "Nhạc cụ dân tộc với nhiều dây, thường dùng trong nhạc truyền thống." },
    { word: "phoco", display: "Phố Cổ", hint: "Khu phố nổi tiếng với kiến trúc cổ ở Hà Nội." },
    { word: "saigon", display: "Sài Gòn", hint: "Tên gọi cũ của thành phố Hồ Chí Minh." },
    { word: "chualinhung", display: "Chùa Linh Ứng", hint: "Ngôi chùa nổi tiếng ở Đà Nẵng, có tượng Phật Quan Âm lớn." },
    { word: "caodai", display: "Cao Đài", hint: "Tôn giáo đặc trưng xuất phát từ Tây Ninh." },
    { word: "tugiac", display: "Nón Tứ Giác", hint: "Tên gọi khác của chiếc nón lá truyền thống." },
    { word: "hoian", display: "Hội An", hint: "Phố cổ nổi tiếng với đèn lồng và di sản thế giới." },
    { word: "bentre", display: "Bến Tre", hint: "Tỉnh miền Tây nổi tiếng với dừa." },
    { word: "cuchitunnel", display: "Địa Đạo Củ Chi", hint: "Địa đạo nổi tiếng ở miền Nam, di tích lịch sử thời chiến tranh." },
    { word: "battrang", display: "Bát Tràng", hint: "Làng nghề truyền thống nổi tiếng ở Bát Tràng." },
    { word: "caolanh", display: "Cao Lãnh", hint: "Thành phố thuộc tỉnh Đồng Tháp, nổi tiếng với sen." },
    { word: "banhxeo", display: "Bánh Xèo", hint: "Món bánh đặc sản miền Trung và miền Nam, vỏ giòn, nhân tôm thịt." },
    { word: "chungcake", display: "Bánh Chưng", hint: "Tên tiếng Anh của món bánh truyền thống ngày Tết." },
    { word: "sapa", display: "Sa Pa", hint: "Thị trấn nổi tiếng với ruộng bậc thang và khí hậu mát mẻ ở Lào Cai." },
    { word: "tayninh", display: "Tây Ninh", hint: "Nơi xuất phát của đạo Cao Đài, nổi tiếng với núi Bà Đen." },
    { word: "dalat", display: "Đà Lạt", hint: "Thành phố ngàn hoa, nổi tiếng với khí hậu ôn hòa và hồ Xuân Hương." },
    { word: "myson", display: "Mỹ Sơn", hint: "Khu di tích tháp Chăm nổi tiếng ở Quảng Nam." },
    { word: "vungtau", display: "Vũng Tàu", hint: "Thành phố biển nổi tiếng gần Sài Gòn, có tượng Chúa Kitô lớn." },
    { word: "bennghe", display: "Bến Nghé", hint: "Tên một con kênh nổi tiếng ở Sài Gòn." },
    { word: "camau", display: "Cà Mau", hint: "Tỉnh cực Nam của Việt Nam, nổi tiếng với rừng U Minh." },
    { word: "phuquoc", display: "Phú Quốc", hint: "Hòn đảo lớn nhất Việt Nam, nổi tiếng với nước mắm và bãi biển đẹp." },
    { word: "langsen", display: "Làng Sen", hint: "Lễ hội truyền thống lớn ở Bắc Ninh, gắn với Quan họ." },
    { word: "quangninh", display: "Quảng Ninh", hint: "Tỉnh có vịnh Hạ Long, di sản thiên nhiên thế giới." },
    { word: "bavi", display: "Ba Vì", hint: "Dãy núi nổi tiếng gần Hà Nội, có vườn quốc gia." },
    { word: "nghean", display: "Nghệ An", hint: "Quê hương của Chủ tịch Hồ Chí Minh." },
    { word: "tuyenquang", display: "Tuyên Quang", hint: "Nơi tổ chức lễ hội Thành Tuyên với đèn trung thu khổng lồ." },
    { word: "yenbai", display: "Yên Bái", hint: "Nơi có ruộng bậc thang Mù Cang Chải nổi tiếng." },
    { word: "bacninh", display: "Bắc Ninh", hint: "Nơi phát tích dân ca Quan họ." },
    { word: "huefestival", display: "Festival Huế", hint: "Lễ hội văn hóa nghệ thuật lớn tổ chức định kỳ ở cố đô." },
    { word: "phongnha", display: "Phong Nha", hint: "Động nổi tiếng ở Quảng Bình, di sản thiên nhiên thế giới." },
    { word: "trangan", display: "Tràng An", hint: "Quần thể danh thắng nổi tiếng ở Ninh Bình, di sản thế giới." },
    { word: "cailuong", display: "Cải Lương", hint: "Loại hình nghệ thuật sân khấu truyền thống miền Nam." },
    { word: "cheo", display: "Chèo", hint: "Loại hình nghệ thuật sân khấu truyền thống miền Bắc." },
    { word: "tuong", display: "Tuồng", hint: "Loại hình nghệ thuật sân khấu truyền thống miền Trung." },
    { word: "bactrungnam", display: "Bắc Trung Nam", hint: "Cụm từ chỉ ba miền lớn của Việt Nam." },
    { word: "banhcuon", display: "Bánh Cuốn", hint: "Món ăn sáng phổ biến ở miền Bắc, làm từ bột gạo hấp mỏng." },
    { word: "caolau", display: "Cao Lầu", hint: "Món mì đặc sản nổi tiếng của Hội An." },
    { word: "banhda", display: "Bánh Đa", hint: "Loại bánh tráng nướng giòn, thường ăn kèm bún chả." },
    { word: "muine", display: "Mũi Né", hint: "Khu du lịch nổi tiếng với đồi cát ở Bình Thuận." },
    { word: "chaca", display: "Chả Cá", hint: "Món cá nướng nổi tiếng ở Hà Nội, thường ăn với bún và rau thơm." },
    { word: "dinhdoclap", display: "Dinh Độc Lập", hint: "Di tích lịch sử nổi tiếng ở TP.HCM, nơi diễn ra sự kiện 30/4/1975." },
    { word: "banhgio", display: "Bánh Giò", hint: "Món bánh làm từ bột gạo, nhân thịt, hình chóp, ăn sáng phổ biến." },
    { word: "coto", display: "Cô Tô", hint: "Hòn đảo du lịch nổi tiếng ở Quảng Ninh." },
    { word: "baidinh", display: "Bái Đính", hint: "Quần thể chùa lớn nhất Việt Nam, nằm ở Ninh Bình." },
    { word: "banhkhuc", display: "Bánh Khúc", hint: "Món bánh làm từ lá khúc, nhân đậu xanh, thịt mỡ, đặc sản Hà Nội." },
    { word: "caolanh", display: "Cao Lãnh", hint: "Thành phố nổi tiếng với sen ở Đồng Tháp." },
    { word: "banhtrang", display: "Bánh Tráng", hint: "Loại bánh mỏng làm từ bột gạo, dùng cuốn các món ăn miền Nam." },
    { word: "banhbo", display: "Bánh Bò", hint: "Món bánh ngọt, xốp, đặc sản miền Nam." },
    { word: "banhcam", display: "Bánh Cam", hint: "Món bánh tròn, chiên giòn, nhân đậu xanh, đặc sản miền Nam." },
    { word: "banhphu", display: "Bánh Phu Thê", hint: "Món bánh truyền thống của người Hoa ở Chợ Lớn, TP.HCM." },
    { word: "banhduc", display: "Bánh Đúc", hint: "Món bánh làm từ bột gạo, ăn với nước mắm hoặc mật mía." },
    { word: "banhday", display: "Bánh Dày", hint: "Món bánh truyền thống làm từ gạo nếp, tượng trưng cho trời." },
    { word: "banhbao", display: "Bánh Bao", hint: "Món bánh hấp, nhân thịt, trứng, phổ biến ở Việt Nam." },
    { word: "banhchao", display: "Bánh Chạo", hint: "Món bánh chiên giòn, nhân tôm thịt, đặc sản miền Tây." },
];
